export let state = {
  linksPorPai: [],
  linksAcessados: [],
  linkPagina: [],
  edges: '',
  xmlSite: '',
  numPagina: 1,
  numComponente: 1,
  numEvento: 1,
  numState: 1,
  index: 'true',
  domAtual: '',
  itemAtual: 0,
  gravando: false,
  xmlTracer: '',
  inputsAtuais: [],
  iframesAtuais: [],
  ultimaInteracao: '',
  xmlInteracoes: '',
  numInteracoes: 1,
  tempoInteracao: 0,
  xmlFinalTracer: '',
  xmlJquery: ''
};